 language: python
 python:
  - "3.6"
 install:
  - "pip install -r requirements.txt"
  - pip install coveralls
  - pip install pytest-cov  
script:
  - py.test coveralls/test_endpoints.py --doctest-modules --pep8 coveralls -v --cov coveralls --cov-report term-missing
after_success:
  - coveralls

