 language: python
 python:
  - "3.6"
 install:
  - "pip install -r requirements.txt"
  - pip install coveralls
 script:
  - python -m py.test ./tests/test_endpoints.py --cov=app
 after_success:
  - coveralls
